medicalsystem/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using constrng;
using System.Web.Security;

namespace medicalsystem.Controllers
{
    public class UserManagementController : Controller
    {
        // GET: UserManagement
        //use allow anonymous to for skip role checking
        [AllowAnonymous]
        public ActionResult Index()
        {  
            return View();
        }
        //use allow anonymous to for skip role checking
       [AllowAnonymous]
        [HttpPost]
        public ActionResult Index(string txtusername, string txtpass)
        {
            if (DataServices.Services.LoginService.Instance.LoginAuth(txtusername, txtpass)) {
                Session["Logged_in"] = true;
                FormsAuthentication.SetAuthCookie(txtusername, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Error = "Invalid Username or Password!";
                return View();
                //return RedirectToAction("Index", "UserManagement");
            }         
        }



    }
}

medicalsystem/Views/UserManagement/Index.cshtml
@inherits System.Web.Mvc.WebViewPage
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_usermanagement.cshtml";
}

<div class="container">
    <div class="row text-center ">
        <div class="col-md-12">
            <br /><br />
            <h2> Pharmacy Management : Login</h2>

            <h5>( Login yourself to get access )</h5>
            <br />
        </div>
    </div>
    <div class="row ">

        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>   Enter Details To Login </strong>
                </div>
                <div class="panel-body">
                    <form role="form" method="post">
                        <br />
                        @{ if (ViewBag.Error != null)
                            {
<div class="alert alert-danger fade in">
                                    <strong>
                                        <label id="lblErrormsg" name="lblErrormsg">@ViewBag.Error</label>
                                    </strong>
                                </div>
                            }
                        }
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-tag"></i></span>
                            <input type="text" name="txtusername" class="form-control" placeholder="Your Username " />
                        </div>
                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                            <input type="password" name="txtpass" class="form-control" placeholder="Your Password" />
                        </div>

                        <div class="form-group">
                            <label class="checkbox-inline">
                                <input type="checkbox" /> Remember me
                            </label>
                            <span class="pull-right">
                                <a href="#">Forget password ? </a>
                            </span>
                        </div>

                        <input type="submit" class="btn btn-primary" value="Login Now" />
                        @*<a href="@Url.Action("Login", "UserManagement")" class="btn btn-primary ">Login Now</a>*@
                        <hr />
                        Not register ? <a href="#">click here </a>
                    </form>
                </div>

            </div>
        </div>


    </div>
</div>