medicalsystem/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using constrng;
using System.Web.Security;
using medicalsystem.Models;
namespace medicalsystem.Controllers
{
    [Authorize(Roles = "A")]
    public class CompanyController : Controller
    {
        // GET: Company
        
        public ActionResult Index()
        {
            CompanyModel model = new CompanyModel();
            model.CompanyDetails = DataServices.Services.CompanyService.Instance.Companies();
            //var result = DataServices.Services.CompanyService.Instance.Companies();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(tblCompay company)
        {
            DataServices.Services.CompanyService.Instance.AddCompany(company);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var getCompanyForEdit = DataServices.Services.CompanyService.Instance.EditCompany(id);
            return View(getCompanyForEdit);
        }

        [HttpPost]
        public ActionResult Edit(tblCompay  comp, int id)
        {
            DataServices.Services.CompanyService.Instance.UpdateCompany(comp,id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            DataServices.Services.CompanyService.Instance.DeleteCompany(id);
            return RedirectToAction("Index");
        }

    }
}

medicalsystem/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using constrng;

namespace medicalsystem.Controllers
{
    
    public class ProductController : Controller
    {
        // GET: Product
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(DataServices.Services.ProductService.Instance.getproducts());
           
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.gettypes = new SelectList(DataServices.Services.ProductService.Instance.listoftypes(), "TypeId", "TypeName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(tblProduct product)
        {
            DataServices.Services.ProductService.Instance.AddProduct(product);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var getCompanyForEdit = DataServices.Services.ProductService.Instance.EditProduct(id);
            ViewBag.gettypes = new SelectList(DataServices.Services.ProductService.Instance.listoftypes(), "TypeId", "TypeName");
            return View(getCompanyForEdit);
        }

        [HttpPost]
        public ActionResult Edit(tblProduct prod,int id)
        {
            DataServices.Services.ProductService.Instance.UpdateProduct(prod,id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult delete(int id)
        {
            DataServices.Services.ProductService.Instance.DeleteProduct(id);
            return RedirectToAction("index");
        }
    }
}

medicalsystem/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using constrng;
using System.Web.Security;

namespace medicalsystem.Controllers
{
    public class UserManagementController : Controller
    {
        // GET: UserManagement
        //use allow anonymous to for skip role checking
        [AllowAnonymous]
        public ActionResult Index()
        {  
            return View();
        }
        //use allow anonymous to for skip role checking
       [AllowAnonymous]
        [HttpPost]
        public ActionResult Index(string txtusername, string txtpass)
        {
            if (DataServices.Services.LoginService.Instance.LoginAuth(txtusername, txtpass)) {
                Session["Logged_in"] = true;
                FormsAuthentication.SetAuthCookie(txtusername, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Error = "Invalid Username or Password!";
                return View();
                //return RedirectToAction("Index", "UserManagement");
            }         
        }



    }
}

medicalsystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

medicalsystem/Views/Shared/_mytemplate.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hello</title>

    @*@Url.Content("~/Content/css/font-awesome.css")*@

    <!-- BOOTSTRAP STYLES-->
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/Content/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/Content/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="~/Content/datepicker/datepicker3.min.css" rel="stylesheet" />
    <link href="~/Content/datepicker/datepicker.min.css" rel="stylesheet" />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a class="navbar-brand" href="index.html">TAJ-MEDICAL</a>*@
                @Html.ActionLink("TAJ-MEDICAL", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;">Last access : 30 May 2014 &nbsp;<a href="#" class="btn btn-danger square-btn-adjust">Logout</a></div>
        </nav>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li class="text-center">
                        <img src="~/Content/img/find_user.png" class="user-image img-responsive" />
                    </li>

                     @*<span class="fa fa-edit fa-3x" ></span>*@
                    
                    <li>
                       > @Html.ActionLink("Companies", "Index", "Company")
                    </li>
                    <li>
                        @Html.ActionLink("Medicien Type", "Index", "MedicationType")
                    </li>
                    <li>
                        @Html.ActionLink("Products", "Index", "Product")
                    </li>
                    <li>
                        @Html.ActionLink("Dealers", "Index", "Dealers")
                    </li>
                    <li>
                        @Html.ActionLink("Product Recieved", "Index", "ProductRecieved")
                    </li>
                    <li>
                        <a href="form.html"><i class="fa fa-edit fa-3x"></i> Forms </a>
                    </li>
                    <li>
                        <a href="login.html"><i class="fa fa-bolt fa-3x"></i> Login</a>
                    </li>
                    <li>
                        <a href="registeration.html"><i class="fa fa-laptop fa-3x"></i> Registeration</a>
                    </li>


                </ul>


            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            @RenderBody()
                        </div>
                    </div>

                </div>
                <!-- /. ROW  -->
                <hr />

            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <div id="wrap">
        <footer>
            <div class="container">
                <p class="text-muted">Place sticky footer content here.</p>
            </div>
        </footer>
    </div>
    
    <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="~/Content/js/jquery-1.10.2.js"></script>
    
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/Content/js/bootstrap.min.js"></script>

    @RenderSection("pagescript", required: false);

    <!-- METISMENU SCRIPTS -->
    <script src="~/Content/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/Content/js/custom.js"></script>
   
    <script src="http://formvalidation.io/vendor/formvalidation/js/formValidation.min.js"></script>
    @*<script src="http://formvalidation.io/vendor/formvalidation/js/framework/bootstrap.min.js"></script>*@

    <script src="~/scripts/jquery-1.10.2.js"></script>
    <script src="~/scripts/jquery.validate.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Content/datepicker/bootstrap-datepicker.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

medicalsystem/Views/Shared/_usermanagement.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> </title>
    <!-- BOOTSTRAP STYLES-->
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/Content/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/Content/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>
<body>
    
    <div>
        @RenderBody()
    </div>
 
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="~/Content/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="~/Content/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/Content/js/custom.js"></script>
</body>
</html>